# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrant Settings
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.hostname = "master1"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.0.2"

  config.vm.provision "shell", inline: <<-SHELL
    echo "Prática 1: Virtualização com Kubernets" > /tmp/ansible.txt
  SHELL

  #Virtualbox Settings
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "Centos-Master"
    vb.memory = "1024"
    vb.cpus = "2"
  end
end
