- hosts: master
  become: yes
  tasks:
    - name: Configurando NodeIP
      lineinfile:
        path: /etc/default/kubelet
       #line: KUBELET_EXTRA_ARGS=--node-ip={{ node_ip }}
        line: KUBELET_EXTRA_ARGS=--node-ip=192.168.0.2
        create: yes

    - name: Reiniciando o Kubelet
      service:
        name: kubelet
        daemon_reload: yes
        state: restarted