--- 
#---------------------------------------------------------------
# Informação
# autor: Leonardo Viana Pereira
# email: leonardo.viana@armateus.com.br
# version: 0.1.0
# Descrição: Instalando e configurando clusters kubernetes,
# Instalando e configuranado docker nos nós, 
# Ingressando os nós ao cluster.
# Desafio do Curso de DevOps | Ithappens - Referente aos módulos 3 e 4
#---------------------------------------------------------------
#

- name: Desabilitar swap em todos os nodes
  hosts: all
  become: yes
  
  roles:
    - swap

- name: Criar usuário ansible em todos os nodes
  hosts: all
  become: yes
  
  roles:    
    - usuarios

- name: Instalação e configuração do docker em todos os nodes
  hosts: all
  become: yes
  
  roles:    
    - docker

- name: Instalação e configuração kubernetes (kubelet e kubeadm) em todos os nodes
  hosts: all
  become: yes
  
  roles:
    - kubernetes

- name: Instalação do kubectl e configuração do cluster
  hosts: master
  become: yes
  
  roles:
    - master

- name: Ingressando no cluster
  hosts: worker
  become: yes
  
  roles:
    - worker



