#---------------------------------------------------------------
# Informação
# autor: Leonardo Viana Pereira
# email: leonardo.viana@armateus.com.br
# version: 0.1.0
# Descrição: Criando e configurando uma VPC e instâncias EC2 na AWS
# Desafio do Curso de DevOps | Ithappens - Referente aos módulos 3 e 4
#---------------------------------------------------------------

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring-deployment
spec:
  selector:
    matchLabels:
      app: spring-deploy
  template:
    metadata:
      labels:
        app: spring-deploy
    spec:
      containers:
      - name: spring-deploy-app
        image: leoviana00/app-spring 
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: spring-service
spec:
  type: NodePort
  selector:
    app: spring-deploy
  ports:
  - port: 8080
    nodePort: 30005
    targetPort: 8080
    protocol: TCP
  selector:
    app: spring-deploy


