apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-deployment
  labels:
    app: spring-deployment
spec:
  selector:
    matchLabels:
      app: spring-deploy
  template:
    metadata:
      labels:
        app: spring-deploy
    spec:
      containers:
      - name: spring-deploy-app
        image: leoviana00/app-spring 
        ports:
        - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: spring-service
spec:
  selector:
    app: spring-deploy
  ports:
  - protocol: TCP
    port: 8080
    NodePort: 30005
  type: NodePort